// <auto-generated />
using System;
using GariCuvari.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GariCuvari.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250915152059_AddDruzenjaEntity")]
    partial class AddDruzenjaEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DruzenjeGari", b =>
                {
                    b.Property<Guid>("DruzenjaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GarisId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DruzenjaId", "GarisId");

                    b.HasIndex("GarisId");

                    b.ToTable("DruzenjeGari");
                });

            modelBuilder.Entity("GariCuvari.Models.Entities.Druzenje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Druzenja");
                });

            modelBuilder.Entity("GariCuvari.Models.Entities.Gari", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Closeness")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Garis");
                });

            modelBuilder.Entity("DruzenjeGari", b =>
                {
                    b.HasOne("GariCuvari.Models.Entities.Druzenje", null)
                        .WithMany()
                        .HasForeignKey("DruzenjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GariCuvari.Models.Entities.Gari", null)
                        .WithMany()
                        .HasForeignKey("GarisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
